[package]
name = "c_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = "4.5.21"
regex = "1.11.1"
tempfile = "3.14.0"
global_counter = "0.2.2"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "parse_benchmark"
harness = false